# REQUIRED converters
key.converter=org.apache.kafka.connect.storage.StringConverter
value.converter=org.apache.kafka.connect.json.JsonConverter
value.converter.schemas.enable=false

# Kafka cluster
bootstrap.servers=broker-1:9092,broker-2:9092,broker-3:9092
group.id=connect-cluster

# REQUIRED internal topics
config.storage.topic=_connect-configs
offset.storage.topic=_connect-offsets
status.storage.topic=_connect-status

# Replication factors (you have 3 brokers)
config.storage.replication.factor=3
offset.storage.replication.factor=3
status.storage.replication.factor=3

# Plugins (so Connect scans your mounted folder)
plugin.path=/opt/kafka/plugins
# Force plugin directory scanning so external connector JARs are discovered
plugin.discovery=only_scan
